Офицер "Синий Щит"
Bluespace-community/Bluespace-station-new pull request #12
Opened 2024-09-09 17:33 UTC by ChubciYT

**Описание PR**
Обновляет СРП Офицеру "Синего Щита"  

 **Медиа** 
  

 **Проверки** 
  
 - [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить. 
 - [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл. 
 - [ ] Я запускал локальный сервер со своими изменениями и всё протестировал. 
 - [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует. 

 **Изменения** 
 

:cl: ChubciYT

- tweak: Изменено СРП должности Офицер "Синий Щит"

2024-09-09 18:23 UTC, fedKotikeD requested changes
Необходимо переименовать файл на `blueshield.ftl` плюс добавить отступы

2024-09-09 18:23 UTC, fedKotikeD commented on Resources/Locale/ru-RU/Bluespace/BlueShield
> +книга-текст-srpblueshieldsrpblueshield =
```suggestion
book-text-srpblueshieldsrpblueshield =
```

2024-09-11 20:52 UTC, Not-Kluwen approved these changes

2024-09-15 19:47 UTC, fedKotikeD approved these changes
если вдруг из-за отступов или чего-то другого не заработает, я не виноват

2024-09-15 19:48 UTC, merged