Офицер «Синий щит»
Bluespace-community/Bluespace-station-new pull request #7
Opened 2024-09-03 18:20 UTC by fedKotikeD

**Описание PR**
  
Добавляет новую профессию, трекер таймера, и спавнер. в будущей разработке добавлю кпк и айди карту, плюс замапплю спавнер для него. также добавлю срп в виде предмета-книги

 **Медиа** 
  
будет позже

 **Проверки** 
  
 - [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить. 
 - [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл. 
 - [x] Я запускал локальный сервер со своими изменениями и всё протестировал. 
 - [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует. 

 **Изменения** 
 

:cl: fedKotikeD
- add: Добавлена новая должность - Офицер «Синий щит»

2024-09-03 19:10 UTC, Verslebas commented
Запихивать все в один файлик не очень то по людски

2024-09-03 19:11 UTC, fedKotikeD commented
мне впадлу потом с конфликтами драться

2024-09-03 19:12 UTC, Verslebas commented
так в оригинальные файлы то что можно вынести тоже не надо, ты создаешь свою директорию куда и складываешь изменения

2024-09-03 19:12 UTC, Verslebas commented
тогда и конфликтов меньше

2024-09-03 19:13 UTC, fedKotikeD commented
хорошо, завтра этим займусь. щас сделаю КПК и оставшиеся переводы, завтра расфасую по папкам и заодно спавнеры расставлю

2024-09-03 19:16 UTC, fedKotikeD commented
хотя наверное сейчас этим займусь, делать больше нечего. кстати у нас кто-то планировал делать новый отдел, получается все эти лоадауты и тд будут редактироваться. это ещё одна причина распихать их по файлам

2024-09-03 19:20 UTC, fedKotikeD commented
не самое лучшее распределение, но лучше чем всё в одном, не так ли?

2024-09-03 20:24 UTC, fedKotikeD commented
https://rutube.ru/video/private/f03c6ade71f15c83e159119ba569ab59/?p=Aa-qELtiFLhsLKXFXL1ptw

2024-09-04 14:15 UTC, Not-Kluwen requested changes

2024-09-04 14:15 UTC, Not-Kluwen commented on Resources/Locale/ru-RU/preferences/loadout-groups.ftl
> +loadout-group-captain-backpack = ОСЩ, рюкзак
```suggestion
loadout-group-blueshield-backpack = ОСЩ, рюкзак
```

2024-09-04 14:15 UTC, Not-Kluwen commented on Resources/Locale/ru-RU/preferences/loadout-groups.ftl
> +loadout-group-captain-outerclothing = ОСЩ, бронежилет
```suggestion
loadout-group-blueshield-outerclothing = ОСЩ, бронежилет
```

2024-09-04 14:15 UTC, Not-Kluwen commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/pda.ftl
> +    .desc = Враг?! Ой, капитан.. Извините.
Странное описание.. Уверен что не стоит поменять?

2024-09-04 14:15 UTC, Not-Kluwen commented on Resources/Prototypes/Roles/Jobs/Command/blue_shield.yml
> +      requiredAge: 21
```suggestion
      requiredAge: 30
```
Мне так хочется, это не обязательно

2024-09-04 14:15 UTC, Not-Kluwen commented on Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
> -  whitelisted: true
Предлагаю вынести удаление ВЛа в отдельный PR

2024-09-04 14:15 UTC, Not-Kluwen commented on Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
> -  whitelisted: true
Предлагаю вынести удаление ВЛа в отдельный PR

2024-09-04 14:40 UTC, fedKotikeD commented on Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
> -  whitelisted: true
хорошо

2024-09-04 14:40 UTC, fedKotikeD commented on Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
> -  whitelisted: true
хорошо

2024-09-04 14:40 UTC, fedKotikeD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/pda.ftl
> +    .desc = Враг?! Ой, капитан.. Извините.
как по мне норм

2024-09-04 14:41 UTC, Not-Kluwen approved these changes

2024-09-04 15:04 UTC, merged